<a href="https://colab.research.google.com/github/abihaittfaq-create/DREAM-HOME-Real-Estate-Property-platform/blob/main/Real_Estate_AI_Lead_Scoring.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import json

In [2]:
from google.colab import files

uploaded = files.upload()

Saving inquiries (1).json to inquiries (1).json

In [3]:
with open("inquiries (1).json", "r") as f:
    data = json.load(f)

df = pd.DataFrame(data)

df.head()

,inquiryId,propertyId,budget,location,timeline,message
0,I001,P052,177486,Karachi,Within 1 month,I am ready to buy and would like a viewing.
1,I002,P030,304864,Islamabad,Just browsing,Need more details before making a decision.
2,I003,P077,145423,Islamabad,Within 1 month,Need more details before making a decision.
3,I004,P067,293340,Faisalabad,6 months,I am ready to buy and would like a viewing.
4,I005,P070,384442,Lahore,Within 1 month,Just exploring options.

In [4]:
print(df.info())
print(df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   inquiryId   50 non-null     object
 1   propertyId  50 non-null     object
 2   budget      50 non-null     int64
 3   location    50 non-null     object
 4   timeline    50 non-null     object
 5   message     50 non-null     object
dtypes: int64(1), object(5)
memory usage: 2.5+ KB
None
  inquiryId propertyId  budget    location        timeline  \
0      I001       P052  177486     Karachi  Within 1 month
1      I002       P030  304864   Islamabad   Just browsing
2      I003       P077  145423   Islamabad  Within 1 month
3      I004       P067  293340  Faisalabad        6 months
4      I005       P070  384442      Lahore  Within 1 month

                                       message
0  I am ready to buy and would like a viewing.
1  Need more details before making a decision.
2  Need more details before making a decision.
3  I am ready to buy and would like a viewing.
4                      Just exploring options.

In [5]:
def get_intent(message):

    message = message.lower()

    if "ready to buy" in message:
        return "Buying Intent"

    elif "need more details" in message:
        return "Information Request"

    elif "contact me" in message:
        return "Contact Request"

    elif "exploring options" in message:
        return "Browsing"

    else:
        return "Other"

In [6]:
df["Intent"] = df["message"].apply(get_intent)

df[["message","Intent"]].head(10)

                                       message               Intent
0  I am ready to buy and would like a viewing.        Buying Intent
1  Need more details before making a decision.  Information Request
2  Need more details before making a decision.  Information Request
3  I am ready to buy and would like a viewing.        Buying Intent
4                      Just exploring options.             Browsing
5                      Just exploring options.             Browsing
6  I am ready to buy and would like a viewing.        Buying Intent
7  I am ready to buy and would like a viewing.        Buying Intent
8   Please contact me regarding this property.      Contact Request
9  I am ready to buy and would like a viewing.        Buying Intent

In [7]:
def lead_score(row):

    score = 0

    # Timeline Score
    if row["timeline"] == "Within 1 month":
        score += 40

    elif row["timeline"] == "Within 3 months":
        score += 25

    elif row["timeline"] == "6 months":
        score += 15

    else:
        score += 5

    # Intent Score
    if row["Intent"] == "Buying Intent":
        score += 40

    elif row["Intent"] == "Contact Request":
        score += 30

    elif row["Intent"] == "Information Request":
        score += 20

    elif row["Intent"] == "Browsing":
        score += 10

    return score

In [8]:
df["Lead Score"] = df.apply(lead_score, axis=1)

df.head()

,inquiryId,propertyId,budget,location,timeline,message,Intent,Lead Score
0,I001,P052,177486,Karachi,Within 1 month,I am ready to buy and would like a viewing.,Buying Intent,80
1,I002,P030,304864,Islamabad,Just browsing,Need more details before making a decision.,Information Request,25
2,I003,P077,145423,Islamabad,Within 1 month,Need more details before making a decision.,Information Request,60
3,I004,P067,293340,Faisalabad,6 months,I am ready to buy and would like a viewing.,Buying Intent,55
4,I005,P070,384442,Lahore,Within 1 month,Just exploring options.,Browsing,50

In [9]:
def lead_category(score):

    if score >= 70:
        return "Hot Lead"

    elif score >= 40:
        return "Warm Lead"

    else:
        return "Cold Lead"

In [10]:
df["Lead Category"] = df["Lead Score"].apply(lead_category)

df.head(20)

,inquiryId,propertyId,budget,location,timeline,message,Intent,Lead Score,Lead Category
0,I001,P052,177486,Karachi,Within 1 month,I am ready to buy and would like a viewing.,Buying Intent,80,Hot Lead
1,I002,P030,304864,Islamabad,Just browsing,Need more details before making a decision.,Information Request,25,Cold Lead
2,I003,P077,145423,Islamabad,Within 1 month,Need more details before making a decision.,Information Request,60,Warm Lead
3,I004,P067,293340,Faisalabad,6 months,I am ready to buy and would like a viewing.,Buying Intent,55,Warm Lead
4,I005,P070,384442,Lahore,Within 1 month,Just exploring options.,Browsing,50,Warm Lead
5,I006,P098,290953,Peshawar,Just browsing,Just exploring options.,Browsing,15,Cold Lead
6,I007,P067,302230,Faisalabad,Just browsing,I am ready to buy and would like a viewing.,Buying Intent,45,Warm Lead
7,I008,P059,245410,Faisalabad,6 months,I am ready to buy and would like a viewing.,Buying Intent,55,Warm Lead
8,I009,P031,206468,Karachi,6 months,Please contact me regarding this property.,Contact Request,45,Warm Lead
9,I010,P022,200270,Faisalabad,6 months,I am ready to buy and would like a viewing.,Buying Intent,55,Warm Lead
10,I011,P069,252503,Faisalabad,Just browsing,Please contact me regarding this property.,Contact Request,35,Cold Lead
11,I012,P081,289829,Peshawar,Within 3 months,Need more details before making a decision.,Information Request,45,Warm Lead
12,I013,P084,224326,Faisalabad,Within 3 months,I am ready to buy and would like a viewing.,Buying Intent,65,Warm Lead
13,I014,P040,220573,Rawalpindi,Just browsing,Just exploring options.,Browsing,15,Cold Lead
14,I015,P007,208761,Peshawar,Just browsing,Please contact me regarding this property.,Contact Request,35,Cold Lead
15,I016,P029,130803,Karachi,Just browsing,Need more details before making a decision.,Information Request,25,Cold Lead
16,I017,P037,185571,Peshawar,6 months,I am ready to buy and would like a viewing.,Buying Intent,55,Warm Lead
17,I018,P076,282719,Peshawar,Just browsing,I am ready to buy and would like a viewing.,Buying Intent,45,Warm Lead
18,I019,P010,333103,Peshawar,Just browsing,Just exploring options.,Browsing,15,Cold Lead
19,I020,P062,313556,Faisalabad,Within 3 months,I am ready to buy and would like a viewing.,Buying Intent,65,Warm Lead

In [11]:
df[["inquiryId",
    "message",
    "Intent",
    "timeline",
    "Lead Score",
    "Lead Category"]]

,inquiryId,message,Intent,timeline,Lead Score,Lead Category
0,I001,I am ready to buy and would like a viewing.,Buying Intent,Within 1 month,80,Hot Lead
1,I002,Need more details before making a decision.,Information Request,Just browsing,25,Cold Lead
2,I003,Need more details before making a decision.,Information Request,Within 1 month,60,Warm Lead
3,I004,I am ready to buy and would like a viewing.,Buying Intent,6 months,55,Warm Lead
4,I005,Just exploring options.,Browsing,Within 1 month,50,Warm Lead
5,I006,Just exploring options.,Browsing,Just browsing,15,Cold Lead
6,I007,I am ready to buy and would like a viewing.,Buying Intent,Just browsing,45,Warm Lead
7,I008,I am ready to buy and would like a viewing.,Buying Intent,6 months,55,Warm Lead
8,I009,Please contact me regarding this property.,Contact Request,6 months,45,Warm Lead
9,I010,I am ready to buy and would like a viewing.,Buying Intent,6 months,55,Warm Lead
10,I011,Please contact me regarding this property.,Contact Request,Just browsing,35,Cold Lead
11,I012,Need more details before making a decision.,Information Request,Within 3 months,45,Warm Lead
12,I013,I am ready to buy and would like a viewing.,Buying Intent,Within 3 months,65,Warm Lead
13,I014,Just exploring options.,Browsing,Just browsing,15,Cold Lead
14,I015,Please contact me regarding this property.,Contact Request,Just browsing,35,Cold Lead
15,I016,Need more details before making a decision.,Information Request,Just browsing,25,Cold Lead
16,I017,I am ready to buy and would like a viewing.,Buying Intent,6 months,55,Warm Lead
17,I018,I am ready to buy and would like a viewing.,Buying Intent,Just browsing,45,Warm Lead
18,I019,Just exploring options.,Browsing,Just browsing,15,Cold Lead
19,I020,I am ready to buy and would like a viewing.,Buying Intent,Within 3 months,65,Warm Lead
20,I021,Need more details before making a decision.,Information Request,Just browsing,25,Cold Lead
21,I022,I am ready to buy and would like a viewing.,Buying Intent,6 months,55,Warm Lead
22,I023,I am ready to buy and would like a viewing.,Buying Intent,Within 3 months,65,Warm Lead
23,I024,Need more details before making a decision.,Information Request,Just browsing,25,Cold Lead
24,I025,I am ready to buy and would like a viewing.,Buying Intent,Within 3 months,65,Warm Lead
25,I026,I am ready to buy and would like a viewing.,Buying Intent,Within 1 month,80,Hot Lead
26,I027,Please contact me regarding this property.,Contact Request,Just browsing,35,Cold Lead
27,I028,I am ready to buy and would like a viewing.,Buying Intent,6 months,55,Warm Lead
28,I029,I am ready to buy and would like a viewing.,Buying Intent,Within 3 months,65,Warm Lead
29,I030,Just exploring options.,Browsing,Within 1 month,50,Warm Lead
30,I031,Please contact me regarding this property.,Contact Request,Within 1 month,70,Hot Lead
31,I032,Need more details before making a decision.,Information Request,6 months,35,Cold Lead
32,I033,Just exploring options.,Browsing,6 months,25,Cold Lead
33,I034,Need more details before making a decision.,Information Request,Within 3 months,45,Warm Lead
34,I035,Need more details before making a decision.,Information Request,Within 1 month,60,Warm Lead
35,I036,Need more details before making a decision.,Information Request,Within 1 month,60,Warm Lead
36,I037,Need more details before making a decision.,Information Request,Just browsing,25,Cold Lead
37,I038,Please contact me regarding this property.,Contact Request,Within 3 months,55,Warm Lead
38,I039,Need more details before making a decision.,Information Request,6 months,35,Cold Lead
39,I040,Need more details before making a decision.,Information Request,Within 1 month,60,Warm Lead
40,I041,Just exploring options.,Browsing,Within 3 months,35,Cold Lead
41,I042,Please contact me regarding this property.,Contact Request,Just browsing,35,Cold Lead
42,I043,Need more details before making a decision.,Information Request,Within 1 month,60,Warm Lead
43,I044,I am ready to buy and would like a viewing.,Buying Intent,Within 1 month,80,Hot Lead
44,I045,Need more details before making a decision.,Information Request,Just browsing,25,Cold Lead
45,I046,Just exploring options.,Browsing,Within 3 months,35,Cold Lead
46,I047,Just exploring options.,Browsing,Within 3 months,35,Cold Lead
47,I048,Just exploring options.,Browsing,Within 1 month,50,Warm Lead
48,I049,Just exploring options.,Browsing,Within 1 month,50,Warm Lead
49,I050,I am ready to buy and would like a viewing.,Buying Intent,Within 1 month,80,Hot Lead

In [ ]:
df.to_csv("Lead_Scoring_Output.csv", index=False)

print("Done!")

In [12]:
# User Input Testing

user_message = input("Enter your inquiry: ")

# Intent Recognition
user_intent = get_intent(user_message)

# User details
user_budget = int(input("Enter your budget: "))
user_timeline = input("Enter your timeline: ")
user_location = input("Enter your location: ")


# Create user data
user_data = {
    "message": user_message,
    "budget": user_budget,
    "timeline": user_timeline,
    "location": user_location,
    "Intent": user_intent
}


# Lead Score
user_score = lead_score(user_data)

# Lead Category
user_category = lead_category(user_score)


# Final Result
print("\n--- Lead Analysis ---")
print("Message:", user_message)
print("Intent:", user_intent)
print("Lead Score:", user_score)
print("Lead Category:", user_category)

Enter your inquiry: i am ready to buy
Enter your budget: 145423
Enter your timeline: 6 months
Enter your location: islamabad

--- Lead Analysis ---
Message: i am ready to buy
Intent: Buying Intent
Lead Score: 55
Lead Category: Warm Lead